apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: capitalone-demo
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: capitalone-demo
  endpoints:
  - port: web
    path: /metrics
