apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitalone-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capitalone-demo
  template:
    metadata:
      labels:
        app: capitalone-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: capitalone-demo
        image: ghcr.io/adroitathena2/devops-ca2-case-study-capitalone:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
